'use strict';
(()=>{
 const base=document.body.dataset.base||'', $=id=>document.getElementById(id);let user,pid='',doc=null,viewText='',viewIds=[],queue=[],busy=false,composing=false,loadBusy=false,counter=0,permanentError=false;
 const client=crypto.randomUUID().replaceAll('-','');const status=text=>$('project-status').textContent=text;
 async function api(path,method='GET',body){const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await response.json();if(!response.ok){const e=new Error(d.error||'Request failed');e.status=response.status;throw e;}return d;}
 function show(id){for(const n of ['project-login','project-list','project-invite','project-workspace'])$(n).hidden=n!==id;}
 function updateDocument(d){const input=$('project-problem');const index=Array.from(viewText.slice(0,input.selectionStart)).length;const anchor=viewIds[index-1];const focused=document.activeElement===input;doc=d;viewText=d.problem;viewIds=d.character_ids;input.value=viewText;if(focused){const i=anchor?viewIds.indexOf(anchor)+1:0;const pos=Array.from(viewText).slice(0,Math.max(0,i)).join('').length;input.setSelectionRange(pos,pos);}$('project-sync').textContent='All changes saved · revision '+d.revision;}
 function metadata(d){$('project-title').textContent=d.title;$('project-invite-btn').hidden=!d.is_owner;const active=d.members.filter(m=>Date.now()/1000-m.seen<15);$('project-presence').textContent=active.map(m=>m.name).join(', ')+(active.length?' · active now':'');$('project-member-list').replaceChildren();for(const m of d.members){const row=document.createElement('div');row.className='project-member';const label=document.createElement('span');label.textContent=m.name+(m.user===d.owner_id?' · owner':'');row.append(label);if(d.is_owner&&m.user!==d.owner_id){const remove=document.createElement('button');remove.textContent='Remove';remove.onclick=async()=>{if(!confirm('Remove this member? Existing invitation links will also be revoked.'))return;try{await api('/api/projects/'+pid+'/remove-member','POST',{user_id:m.user});await poll();}catch(e){status(e.message);}};row.append(remove);}$('project-member-list').append(row);}
 $('project-runs').replaceChildren();for(const r of d.runs){const row=document.createElement('article');row.className='project-result';const info=document.createElement('div');const h=document.createElement('h3');h.textContent=r.task||'Research agent';const p=document.createElement('p');p.textContent=[r.engine,r.status,d.members.find(m=>m.user===r.user)?.name||'Former member'].filter(Boolean).join(' · ');info.append(h,p);row.append(info);if(r.status!=='deleted'){const a=document.createElement('a');a.textContent='Open run →';a.href=base+'/?run='+encodeURIComponent(r.run_id);row.append(a);}$('project-runs').append(row);}if(!d.runs.length)$('project-runs').textContent='No runs yet. Launch an agent to add the first result.';}
 function capture(){if(composing)return;const next=$('project-problem').value;const a=Array.from(viewText),b=Array.from(next);let first=0;while(first<a.length&&first<b.length&&a[first]===b[first])first++;let end=0;while(end<a.length-first&&end<b.length-first&&a[a.length-1-end]===b[b.length-1-end])end++;const removed=viewIds.slice(first,a.length-end);for(const id of removed)queue.push({type:'delete',id});let after=first?viewIds[first-1]:'';const inserted=[];for(const value of b.slice(first,b.length-end)){const id=client+':'+(++counter);queue.push({type:'insert',id,after,value});inserted.push(id);after=id;}viewIds=[...viewIds.slice(0,first),...inserted,...viewIds.slice(a.length-end)];viewText=next;$('project-sync').textContent='Saving…';}
 async function flush(){if(!pid||busy||composing||!queue.length||permanentError)return;busy=true;const batch=queue.splice(0,2000);try{const d=await api('/api/projects/'+pid+'/edit','POST',{operations:batch});if(!queue.length&&!composing)updateDocument(d);status('');}catch(e){queue.unshift(...batch);permanentError=e.status===400||e.status===404||e.status===401;status(e.message+' Your unsent edits remain in this editor. Copy them before closing.');$('project-sync').textContent='Changes not synced';}finally{busy=false;}}
 async function poll(){if(!pid||loadBusy)return;loadBusy=true;try{const d=await api('/api/projects/'+pid);metadata(d);if(!queue.length&&!busy&&!composing&&(!doc||d.revision>=doc.revision))updateDocument(d);}catch(e){status(e.message);}finally{loadBusy=false;}}
 $('project-problem').addEventListener('compositionstart',()=>composing=true);$('project-problem').addEventListener('compositionend',()=>{composing=false;capture();});$('project-problem').addEventListener('input',capture);
 window.addEventListener('beforeunload',e=>{if(queue.length||busy||composing){e.preventDefault();e.returnValue='';}});
 async function init(){try{const me=await api('/api/auth/me');user=me.user;if(!user||user.guest){show('project-login');status('');return;}const path=location.pathname.slice(base.length);if(path.startsWith('/invite/')){show('project-invite');status('');return;}pid=path.split('/')[2]||'';if(pid){show('project-workspace');await poll();const engines=await api('/api/engines');const list=Array.isArray(engines)?engines:(engines.engines||[]);for(const e of list.filter(e=>e.available)){const o=document.createElement('option');o.value=e.id;o.textContent=e.name||e.id;$('project-engine').append(o);}status('');}else{show('project-list');const d=await api('/api/projects');$('project-cards').replaceChildren();for(const project of d.projects){const a=document.createElement('a');a.className='project-result';a.textContent=project.title;a.href=base+'/projects/'+project.id;$('project-cards').append(a);}status('');}}catch(e){status(e.message);}}
 $('project-retry').onclick=init;
 $('project-create').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/projects','POST',{title:$('project-title-input').value,problem:''});location.href=base+'/projects/'+d.id;}catch(e){status(e.message);}};
 $('project-accept').onclick=async()=>{try{const d=await api('/api/projects/join','POST',{token:location.pathname.split('/').pop()});location.href=base+'/projects/'+d.id;}catch(e){status(e.message);}};
 $('project-invite-btn').onclick=async()=>{try{const d=await api('/api/projects/'+pid+'/invite','POST',{});$('project-invite-url').value=new URL(d.path,location.origin).href;$('project-invite-panel').hidden=false;}catch(e){status(e.message);}};
 $('project-copy').onclick=async()=>{try{await navigator.clipboard.writeText($('project-invite-url').value);status('Invitation copied.');}catch{$('project-invite-url').focus();$('project-invite-url').select();status('Select and copy the invitation above.');}};
 $('project-revoke').onclick=async()=>{try{await api('/api/projects/'+pid+'/invite','POST',{revoke:true});$('project-invite-url').value='';$('project-invite-panel').hidden=true;status('Invitation revoked. Existing members keep their access.');}catch(e){status(e.message);}};
 $('project-run-form').onsubmit=async e=>{e.preventDefault();if(queue.length||busy||composing){status('Wait for your document edits to finish syncing before launching.');return;}const b=$('project-run-btn');b.disabled=true;try{const d=await api('/api/runs','POST',{project_id:pid,project_task:$('project-task').value,engine:$('project-engine').value,model:$('project-model').value||null,use_subagents:true});status('Agent launched. Its result will appear in this project.');await poll();}catch(e){status(e.message);}finally{b.disabled=false;}};
 setInterval(flush,350);setInterval(poll,1500);init();
})();
