'use strict';
(async()=>{
 const $=id=>document.getElementById(id);let data;
 try{const response=await fetch(document.body.dataset.snapshotUrl,{credentials:'omit',cache:'no-store',referrerPolicy:'no-referrer'});if(!response.ok)throw new Error('This run is unavailable. The owner may have revoked the link.');data=await response.json();}catch(e){$('rv-notice').textContent=e.message;return;}
 document.title=(data.title||'Shared run')+' · Ansätze';
 for(const [id,value] of [['rv-title',data.title],['rv-status',data.status],['rv-problem',data.problem],['rv-notice',data.notice],['rv-proof-text',data.proof||'No proof text was included in this snapshot.'],['rv-lean-text',data.lean_source||'No Lean source was included.'],['rv-verification',data.verification?data.verification.version+' · '+data.verification.result:'Source is shown as saved. No new verification is performed when this page is opened.']])$(id).textContent=value||'';
 if(data.source_url&&/^https:\/\//.test(data.source_url)){$('rv-source').href=data.source_url;$('rv-source').hidden=false;}
 (data.agents||[]).forEach((a,i)=>{const card=document.createElement('article');card.className='rv-step';const index=document.createElement('span');index.textContent=String(i+1).padStart(2,'0');const body=document.createElement('div');const h=document.createElement('h3');h.textContent=a.label||'Research step';const meta=document.createElement('small');meta.textContent=[a.status,a.model].filter(Boolean).join(' · ');const p=document.createElement('p');p.textContent=a.summary||'No summary included.';body.append(h,meta,p);card.append(index,body);$('rv-agents').append(card);});
 if(!(data.agents||[]).length)$('rv-agents').textContent='No agent summaries were included in this snapshot.';
 function graph(kind){const g=data[kind+'_graph']||{nodes:[],edges:[]};const nodes=g.nodes||[],edges=g.edges||[];$('rv-graph-title').textContent=g.title||(kind==='formal'?'Lean DAG':'Reasoning DAG');const canvas=$('rv-canvas');canvas.replaceChildren();$('rv-node-detail').textContent=nodes.length?'Select a node.':'No graph was included. Generating a graph is an owner-only action.';if(!nodes.length){canvas.style.height='0';return;}
 const depth=new Map(nodes.map(n=>[n.id,0]));for(let pass=0;pass<nodes.length;pass++){let changed=false;for(const e of edges){if(!depth.has(e.from)||!depth.has(e.to))continue;const d=Math.min(nodes.length-1,depth.get(e.from)+1);if(d>depth.get(e.to)){depth.set(e.to,d);changed=true;}}if(!changed)break;}
 const levels=new Map;for(const n of nodes){const d=depth.get(n.id);if(!levels.has(d))levels.set(d,[]);levels.get(d).push(n);}const width=Math.max(240,...[...levels.values()].map(a=>a.length*232));const height=(Math.max(...depth.values())+1)*150;canvas.style.width=width+'px';canvas.style.height=height+'px';const pos=new Map;for(const [d,row]of levels)row.forEach((n,i)=>pos.set(n.id,{x:(width-row.length*232)/2+i*232+12,y:d*150+12}));
 const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('width',width);svg.setAttribute('height',height);svg.setAttribute('aria-hidden','true');const defs=document.createElementNS(ns,'defs');const marker=document.createElementNS(ns,'marker');for(const[k,v]of Object.entries({id:'rv-arrow',markerWidth:8,markerHeight:8,refX:7,refY:4,orient:'auto'}))marker.setAttribute(k,v);const arrow=document.createElementNS(ns,'path');arrow.setAttribute('d','M0 0 L8 4 L0 8');arrow.setAttribute('fill','#789078');marker.append(arrow);defs.append(marker);svg.append(defs);for(const e of edges){if(!pos.has(e.from)||!pos.has(e.to))continue;const a=pos.get(e.from),b=pos.get(e.to);const p=document.createElementNS(ns,'path');p.setAttribute('d',`M${a.x+104},${a.y+96} C${a.x+104},${a.y+124} ${b.x+104},${b.y-28} ${b.x+104},${b.y-4}`);p.setAttribute('fill','none');p.setAttribute('stroke','#789078');p.setAttribute('stroke-width','2');p.setAttribute('marker-end','url(#rv-arrow)');svg.append(p);}canvas.append(svg);
 for(const n of nodes){const button=document.createElement('button');button.style.left=pos.get(n.id).x+'px';button.style.top=pos.get(n.id).y+'px';button.textContent=n.label||n.id;button.dataset.open=String((n.status||'').includes('open'));const small=document.createElement('small');small.textContent=n.status||n.lean_kind||n.kind||'';button.append(small);button.onclick=()=>{for(const b of canvas.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b===button));const dependencies=edges.filter(e=>e.to===n.id).map(e=>nodes.find(x=>x.id===e.from)?.label||e.from);$('rv-node-detail').textContent=(n.label||n.id)+'\n\n'+(n.statement||'')+'\n\nDepends on: '+(dependencies.join(', ')||'No incoming dependencies');};canvas.append(button);}}
 function tab(name){for(const b of document.querySelectorAll('[data-tab]'))b.setAttribute('aria-pressed',String(b.dataset.tab===name));for(const key of ['agents','proof','graph','lean'])$('rv-'+key).hidden=key!==(['formal','informal'].includes(name)?'graph':name);if(['formal','informal'].includes(name))graph(name);}
 for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>tab(b.dataset.tab);
 const requested=new URL(location.href).searchParams.get('view');if(['formal','informal','lean','proof'].includes(requested))tab(requested);
})();
