/* Run sharing and project entry points, loaded after the console. */
(()=>{
 const base=window.__PC_BASE__||'';
 const link=(text,path)=>{const a=document.createElement('a');a.textContent=text;a.href=base+path;a.className='sess-btn';a.style.cssText='display:inline-block;color:var(--accent);text-decoration:none;margin:8px 12px;';return a;};
 const landing=document.querySelector('#view-landing');if(landing){const row=document.createElement('div');const note=document.createElement('p');note.textContent='Worked example: an open Erdős problem, exact computations, and five Lean-checked witnesses.';note.style.cssText='color:var(--muted);font-size:13px;margin:18px 12px 0;';row.append(note);row.append(link('Explore the Erdős–Straus example ↗','/examples/erdos-straus'),link('Collaborative projects →','/projects'));landing.append(row);}
 const side=document.querySelector('.session-side');if(!side)return;const style=document.createElement('style');style.textContent='.session-top .session-side{max-width:100%;flex-wrap:wrap} @media(max-width:1100px){.session-top{display:flex;flex-wrap:wrap}.session-top .session-side{margin-left:auto}}';document.head.append(style);
 const button=document.createElement('button');button.className='sess-btn show';button.id='share-run-btn';button.textContent='Share';side.prepend(button);
 const dialog=document.createElement('dialog');dialog.style.cssText='width:min(560px,92vw);padding:24px;border:1px solid var(--border);border-radius:12px;background:var(--bg);color:var(--fg);';
 dialog.innerHTML='<h2 style="margin-bottom:12px">Share this run</h2><p>Anyone with the link can view a read-only snapshot of the problem, proof, agent summaries, saved DAGs, and Lean source. Review those texts before sharing. Account settings, chat history, attachments, and other workspace files are excluded.</p><p style="margin:12px 0">The snapshot stays fixed until you update it. Revoking prevents future access; it cannot remove copies someone already saved.</p><label style="display:flex;gap:10px;margin:16px 0"><input type="checkbox" id="share-confirm"> I want to share this snapshot.</label><input id="share-url" readonly aria-label="Shareable run link" style="width:100%;padding:10px;margin-bottom:12px"><p id="share-status" role="status" style="margin:8px 0"></p><div style="display:flex;flex-wrap:wrap;gap:8px"><button id="share-create">Create / update link</button><button id="share-copy">Copy link</button><button id="share-open">Preview</button><button id="share-revoke">Revoke link</button><button id="share-close">Close</button></div>';
 document.body.append(dialog);const $=id=>dialog.querySelector('#'+id);let rid='',url='';
 function state(d){url=d.path?new URL(d.path,location.origin).href:'';$('share-url').value=url;$('share-copy').disabled=!url;$('share-open').disabled=!url;$('share-revoke').disabled=!url;}
 async function api(method,body){const r=await fetch('/api/runs/'+encodeURIComponent(rid)+'/share',{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Sharing failed');return d;}
 button.onclick=async()=>{if(typeof runId==='undefined'||!runId)return;rid=runId;state({});$('share-confirm').checked=false;$('share-status').textContent='Loading…';dialog.showModal();try{state(await api('GET'));$('share-status').textContent='';}catch(e){$('share-status').textContent=e.message;}};
 $('share-create').onclick=async()=>{if(!$('share-confirm').checked){$('share-status').textContent='Select the checkbox to confirm sharing.';return;}const b=$('share-create');b.disabled=true;try{state(await api('POST',{confirm_share:true}));$('share-status').textContent='Snapshot ready. Copy the link or preview it.';}catch(e){$('share-status').textContent=e.message;}finally{b.disabled=false;}};
 $('share-copy').onclick=async()=>{try{await navigator.clipboard.writeText(url);$('share-status').textContent='Link copied.';}catch{$('share-url').focus();$('share-url').select();$('share-status').textContent='Select and copy the link above.';}};
 $('share-open').onclick=()=>window.open(url,'_blank','noopener,noreferrer');
 $('share-revoke').onclick=async()=>{try{state(await api('DELETE'));$('share-status').textContent='Link revoked.';}catch(e){$('share-status').textContent=e.message;}};
 $('share-close').onclick=()=>dialog.close();
 const selected=new URL(location.href).searchParams.get('run');if(selected&&/^[A-Za-z0-9_.-]+$/.test(selected)){selectRun(selected,null);goSession('sandbox');}
})();
