// Run against an isolated docs build with ATLAS_REVIEW_BASE. Research API fixtures
// cover pagination and provenance display without publishing data or creating runs.
const {chromium}=require(process.env.ATLAS_PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const output=process.env.ATLAS_REVIEW_OUTPUT || '/tmp/ansatz-expanded-atlas-review';
fs.mkdirSync(output,{recursive:true});
const base=process.env.ATLAS_REVIEW_BASE||'http://127.0.0.1:4178';
(async()=>{
 const atlas=await fetch(base+'/research/informal-atlas.json').then(response=>{assert.equal(response.ok,true);return response.json()});
 const sourceCount=atlas.nodes.length,fields=[...new Set(atlas.nodes.map(node=>node.area))];
 const formatted=value=>value.toLocaleString('en-US');
 const field=fields.includes('Schemes')?'Schemes':fields[0];
 const fieldCount=atlas.nodes.filter(node=>node.area===field).length;
 const sourceNode=atlas.nodes.find(node=>node.tag==='05N2')||atlas.nodes[0];
 const linkedIds=new Set(atlas.edges.flatMap(edge=>[edge.source,edge.target]));
 const isolated=atlas.nodes.find(node=>!linkedIds.has(node.id));
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const errors=[];
 async function context(options={}){
  const c=await browser.newContext({viewport:{width:1440,height:1050},colorScheme:'light',...options});
  await c.route('**/sign-in',r=>r.fulfill({status:302,headers:{location:'/review/login'}}));
  await c.route('**/review/login',r=>r.fulfill({status:200,contentType:'text/html',body:'Sign in'}));
  await c.route('**/review/api/research/dag**',r=>r.fulfill({json:{memories:[],user:null,policy:{allowed_models:['gpt-6','fable','gpt-5.6-sol']},has_more:false}}));
  c.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
  return c;
 }
 const c=await context(),p=await c.newPage();
 const began=Date.now();
 await p.goto(base+'/dag',{waitUntil:'networkidle'});
 await p.waitForFunction(expected=>Number(document.querySelector('canvas.atlas-canvas')?.dataset.nodeCount)===expected,sourceCount);
 const loadMs=Date.now()-began;
 assert.equal(await p.locator('canvas').count(),1);
 assert.equal(await p.locator('.atlas-canvas').getAttribute('data-visible-count'),String(sourceCount));
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.equal(await p.getByRole('button',{name:'Both layers',exact:true}).count(),0);
 const domCount=await p.locator('*').count();assert.ok(domCount<1300,`DOM contains ${domCount} nodes`);
 await p.screenshot({path:path.join(output,'atlas-desktop.png'),fullPage:true});
 const drawMs=Number(await p.locator('canvas').getAttribute('data-draw-ms'));
 assert.equal(await p.getByLabel('Filter mathematical field').locator('option').count(),fields.length+1);
 await p.getByLabel('Filter mathematical field').selectOption(field);
 await p.waitForFunction(expected=>Number(document.querySelector('.atlas-canvas')?.dataset.visibleCount)===expected,fieldCount);
 await p.screenshot({path:path.join(output,'atlas-field.png'),fullPage:false});
 assert.ok((await p.locator('.atlas-search-summary').innerText()).includes(formatted(fieldCount)+' matching nodes'));
 await p.getByRole('button',{name:'Clear filters',exact:true}).click();
 await p.getByLabel('Find a mathematical idea').fill(sourceNode.tag);
 await p.getByLabel('Find a mathematical idea').press('Enter');
 assert.equal(await p.locator('.atlas-inspector h2').innerText(),sourceNode.title);
 assert.equal(await p.locator('.inspector-source').getAttribute('href'),sourceNode.source_url);
 assert.equal(await p.locator('.inspector-pinned-source').getAttribute('href'),sourceNode.source_git_url);
 await p.getByText('Original mathematical statement',{exact:true}).click();
 assert.equal(await p.getByRole('link',{name:'View pinned source ↗'}).isVisible(),true);
 await p.getByLabel('Find a mathematical idea').fill('');
 await p.getByRole('button',{name:'☷ List',exact:true}).click();
 assert.equal(await p.locator('.atlas-node-list > button').count(),30);
 assert.ok((await p.locator('.atlas-pagination').innerText()).includes('Page 1 / '+formatted(Math.ceil(sourceCount/30))));
 const first=await p.locator('.atlas-node-list > button').first().innerText();
 await p.getByRole('button',{name:'Next →',exact:true}).click();
 assert.notEqual(await p.locator('.atlas-node-list > button').first().innerText(),first);
 await p.locator('.atlas-node-list > button').first().click();
 assert.ok((await p.locator('.atlas-inspector h2').innerText()).length>5);
 await p.getByLabel('Find a mathematical idea').fill('absolutely-no-matching-node-xyz');
 assert.equal(await p.locator('.atlas-node-list > button').count(),0);
 assert.match(await p.locator('.atlas-empty').innerText(),/No matching/);
 await p.getByLabel('Find a mathematical idea').fill('');
 await p.getByRole('button',{name:'◇ Map',exact:true}).click();
 await p.getByRole('button',{name:'Fit',exact:true}).click();
 const beforeZoom=await p.getByLabel('Zoom level').innerText();
 await p.getByRole('button',{name:'Zoom in',exact:true}).click();
 assert.notEqual(await p.getByLabel('Zoom level').innerText(),beforeZoom);
 await p.locator('canvas').focus();await p.keyboard.press('0');
 await p.waitForFunction(expected=>Number(document.querySelector('.atlas-canvas')?.dataset.visibleCount)===expected,sourceCount);
 if(isolated){
  await p.getByLabel('Find a mathematical idea').fill(isolated.tag);
  await p.getByLabel('Find a mathematical idea').press('Enter');
  assert.equal(await p.locator('.atlas-inspector h2').innerText(),isolated.title);
  assert.match(await p.locator('.inspector-no-connections').innerText(),/No direct references/);
  assert.equal(await p.locator('.inspector-source').getAttribute('href'),isolated.source_url);
 }
 await p.getByRole('button',{name:'+ Contribute a completed run',exact:true}).click();
 assert.equal(await p.getByRole('link',{name:'Sign in to contribute →'}).count(),1);
 await p.goto(base+'/',{waitUntil:'networkidle'});
 assert.equal(await p.locator('.atlas-home-preview').count(),1);
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.ok((await p.locator('.atlas-home-preview').innerText()).includes(formatted(sourceCount)+' source-linked nodes'));
 const previewIds=await p.locator('.atlas-preview-map svg > g:nth-of-type(2) circle').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('data-source-id')));
 assert.ok(previewIds.length>0&&previewIds.length<sourceCount);
 const realIds=new Set(atlas.nodes.map(node=>node.id));assert.ok(previewIds.every(id=>realIds.has(id)),'Homepage sample must contain real catalogue IDs');
 await p.locator('.atlas-home-preview').screenshot({path:path.join(output,'atlas-home.png')});
 const mctx=await context({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),m=await mctx.newPage();
 await m.goto(base+'/dag',{waitUntil:'networkidle'});
 await m.waitForFunction(expected=>Number(document.querySelector('.atlas-canvas')?.dataset.visibleCount)===expected,sourceCount);
 assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await m.screenshot({path:path.join(output,'atlas-mobile.png'),fullPage:true});
 await m.getByRole('button',{name:'☷ List',exact:true}).click();
 await m.getByRole('button',{name:'Next →',exact:true}).click();
 await m.locator('.atlas-node-list > button').nth(4).click();
 assert.ok((await m.locator('.atlas-inspector h2').innerText()).length>5);
 await m.getByRole('button',{name:'◇ Map',exact:true}).click();
 await m.getByRole('button',{name:'Fit',exact:true}).click();
 await m.locator('canvas').scrollIntoViewIfNeeded();
 const initialMobileZoom=Number((await m.getByLabel('Zoom level').innerText()).replace('%',''));
 const box=await m.locator('canvas').boundingBox();
 const touch=await mctx.newCDPSession(m);
 const y=box.y+box.height/2,x=box.x+box.width/2;
 await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-30,y},{x:x+30,y}]});
 await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-65,y},{x:x+65,y}]});
 await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await m.waitForFunction(before=>Number(document.querySelector('.atlas-zoom output').textContent.replace('%',''))>before,initialMobileZoom);
 const memoryContext=await context();
 const record=(id,node)=>({id,node_id:node,title:'Eligible result '+id,content:'Preview for '+id,source_run_id:'run-'+id,layer:'informal',model:'gpt-6',is_owner:false});
 let memoryPages=0;
 await memoryContext.route('**/review/api/research/dag**',r=>{
  const url=new URL(r.request().url());
  if(url.pathname.endsWith('/memory-a'))return r.fulfill({json:{memory:{...record('memory-a',sourceNode.id),content:'Full detailed reasoning from the completed eligible run.'}}});
  memoryPages++;
  return r.fulfill({json:{memories:[record(url.searchParams.get('offset')==='0'?'memory-a':'memory-b',sourceNode.id)],has_more:url.searchParams.get('offset')==='0',next_offset:1,policy:{allowed_models:['gpt-6']},user:null}});
 });
 const mp=await memoryContext.newPage();await mp.goto(base+'/dag',{waitUntil:'networkidle'});
 await mp.waitForFunction(expected=>Number(document.querySelector('canvas')?.dataset.nodeCount)===expected,sourceCount+2);
 assert.equal(memoryPages,2);
 await mp.getByLabel('Find a mathematical idea').fill('Eligible result memory-a');
 await mp.getByLabel('Find a mathematical idea').press('Enter');
 await mp.waitForFunction(()=>document.querySelector('.inspector-description')?.textContent.includes('Full detailed reasoning'));
 assert.match(await mp.locator('.inspector-layer').innerText(),/Model-generated/);
 assert.match(await mp.locator('.inspector-connections').innerText(),/Attached to/);
 assert.deepEqual(errors,[]);
 const result={status:'passed',sourceCount,sourceEdges:atlas.edges.length,fieldCount:fields.length,sourceComponents:atlas.stats.weakly_connected_components,loadMs,drawMs,domCount,checks:[`${sourceCount} catalogue nodes all visible at fit`,`${atlas.edges.length} source-reference edges loaded`,`${fields.length} field filters`,'search and source links',`30-item pagination over ${Math.ceil(sourceCount/30)} pages`,'zoom pan keyboard touch pinch','desktop390px-mobile no horizontal overflow','homepage sampled preview','2-page memory fetch and live memory nodes','lazy complete-memory loading','guest contribution flow','zero browser errors'],screenshots:['atlas-desktop.png','atlas-field.png','atlas-mobile.png','atlas-home.png']};
 fs.writeFileSync(path.join(output,'atlas-review.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
